name: goka_app_merchant
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.1.2
  lottie: ^2.3.2
  photo_view: ^0.14.0
  path_provider: ^2.0.4
  adjust_sdk: ^4.29.0
  statusbarz: ^1.0.2
  keyboard_actions: ^4.2.0
  dartx: ^1.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  overlay_support: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  animations: ^2.0.7
  flutter_easyrefresh: ^2.2.1
  expandable: ^5.0.1
  device_info_plus: ^9.0.1
  flutter_styled_toast: ^2.0.0
  flutter_keyboard_visibility: ^5.0.3
  sqflite: ^2.2.8+2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.2
  flutter_native_splash: ^2.2.19
  build_runner: ^2.1.2
  json_serializable: ^6.0.1
  hive_generator: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/images/
